#pragma once

#include <mitsuba/mitsuba.h>
#include <mitsuba/core/bitmap.h>
#include <mitsuba/core/logger.h>
#include <mitsuba/core/object.h>
#include <mitsuba/core/rfilter.h>
#include <mitsuba/core/vector.h>
#include <mitsuba/render/sampler.h>
#include <mitsuba/render/fwd.h>
#include <mitsuba/render/texture.h>
#include <mutex>

NAMESPACE_BEGIN(mitsuba)

/**
 * Abstract film base class - used to store samples generated by `Integrator`
 * implementations.
 *
 * Each sample contributes to nearby pixels according to the film's
 * reconstruction filter. With randomly placed samples, the total filter weight
 * received by a pixel varies, which introduces noise even in trivial scenes,
 * such as a flat surface lit by a point light. The film therefore accumulates
 * filter weights into a weight channel and divides by their sum when developing
 * the image. This removes the noise at the cost of a small bias that vanishes
 * as the sample count increases, i.e., the estimate is consistent.
 *
 * The developed image consists of the film's *base channels* (e.g. ``R``,
 * ``G``, ``B``, and optionally ``A``) followed by the arbitrary output
 * variables (AOVs) of the integrator, such as depth or shading normals. The
 * sample storage holds these channels followed by the weight channel ``W``.
 *
 * Subclasses define the base channels via `base_channels()` and convert
 * spectral samples to them in `prepare_sample()`. Everything else (storage,
 * developing, bitmap conversion) is implemented here.
 *
 * To avoid lock-related bottlenecks in scalar variants, each rendering thread
 * accumulates samples in its own image block (see `create_block()`) and
 * merges it into the film using `put_block()`. JIT variants splat all
 * samples into a single block covering the film.
 */
template <typename Float, typename Spectrum>
class MI_EXPORT_LIB Film : public JitObject<Film<Float, Spectrum>> {
public:
    MI_IMPORT_TYPES(ImageBlock, ReconstructionFilter, Texture, PostProcess)

    /// Destructor
    ~Film();

    /**
     * Names of the base channels of the developed image.
     *
     * Subclasses set these in their constructor. The default is ``R``,
     * ``G``, ``B``.
     */
    const std::vector<std::string> &base_channels() const { return m_base_channels; }

    /// Names of the channels of the developed image (see `develop()`)
    const std::vector<std::string> &channels() const { return m_channels; }

    /**
     * Convert a spectral sample to the film's base channels.
     *
     * The default implementation converts the sample to linear RGB and appends
     * an alpha value when the base channels end with ``A``.
     *
     * Args:
     *     spec: Sample value associated with the specified wavelengths
     *
     *     wavelengths: Sample wavelengths in nanometers
     *
     *     out: Output array with room for one value per base channel
     *
     *     valid: Did the sample intersect the scene? Used to compute alpha.
     *
     *     active: Mask indicating if the lanes are active
     */
    virtual void prepare_sample(const UnpolarizedSpectrum &spec,
                                const Wavelength &wavelengths,
                                Float *out,
                                Mask valid = true,
                                Mask active = true) const;

    /**
     * Configure the film for rendering a specified set of extra channels
     * (AOVs). Returns the total number of channels that the film will store,
     * i.e. the base channels, the AOVs, and the weight channel.
     */
    size_t prepare(const std::vector<std::string> &aovs);

    /// Merge an image block into the film. This method is thread-safe.
    void put_block(const ImageBlock *block);

    /// Clear the film contents to zero.
    void clear();

    /**
     * Return a image buffer object storing the developed image
     *
     * Developing an image normalizes the accumulated samples by the weight
     * channel and runs post-processing filters (if any) on the result.
     *
     * Args:
     *     postprocess: Set this to ``False`` to skip the post-processing
     *         filters and return the linear image.
     */
    TensorXf develop(bool postprocess = true) const;

    /**
     * Return the accumulated samples, i.e. the channels of the developed
     * image followed by the weight channel ``W``, prior to normalization
     */
    TensorXf storage() const;

    /**
     * Return a bitmap object storing the developed contents of the film
     *
     * The parameter has the same meaning as in `develop()`.
     */
    ref<Bitmap> bitmap(bool postprocess = true) const;

    /**
     * Write the developed and post-processed contents of the film to a file on disk
     *
     * When writing 8-bit files (e.g. ``.png``), this operation additionally
     * converts to sRGB gamma.
     */
    virtual void write(const fs::path &path) const;

    /// Post-processing filters declared by the scene, in order
    const std::vector<ref<PostProcess>> &postprocess() const { return m_postprocess; }

    /**
     * Apply the post-processing filters to a developed image
     *
     * Args:
     *     image: Tensor of shape ``(height, width, channels)``, e.g. the
     *         result of ``develop(postprocess=False)``.
     *
     *     channels: Names of the channels along the last axis (e.g. ``R``,
     *         ``G``, ``B``, ``A`` followed by AOV names).
     *
     * Returns:
     *     A tensor with the same shape as ``image``.
     */
    TensorXf apply_postprocess(const TensorXf &image,
                               const std::vector<std::string> &channels) const;

    /**
     * Return an `ImageBlock` instance, whose internal representation
     * is compatible with that of the film.
     *
     * Image blocks created using this method can later be merged into the
     * film using `put_block()`.
     *
     * Args:
     *     size: Desired size of the returned image block.
     *
     *     normalize: Force normalization of filter weights in `ImageBlock.put()`?
     *         See the `ImageBlock` constructor for details.
     *
     *     borders: Should `ImageBlock` add an additional border region around
     *         the image boundary? See the `ImageBlock` constructor for details.
     */
    ref<ImageBlock> create_block(const ScalarVector2u &size = 0,
                                 bool normalize = false,
                                 bool border = false);

    // =============================================================
    // Accessor functions
    // =============================================================

    /**
     * Should regions slightly outside the image plane be sampled to improve
     * the quality of the reconstruction at the edges? This only makes
     * sense when reconstruction filters other than the box filter are used.
     */
    bool sample_border() const { return m_sample_border; }

    /// Ignoring the crop window, return the resolution of the underlying sensor
    const ScalarVector2u &size() const { return m_size; }

    /// Return the size of the crop window
    const ScalarVector2u &crop_size() const { return m_crop_size; }

    /// Return the offset of the crop window
    const ScalarPoint2u &crop_offset() const { return m_crop_offset; }

    /**
     * Set the size and offset of the film's crop window.
     *
     * The caller is responsible to invoke the `parameters_changed()` method on
     * any sensor referring to this film.
     *
     * This function will throw an exception if ``crop_offset + crop_size > size``.
     *
     * Args:
     *     crop_offset: The offset of the crop window.
     *
     *     crop_size: The size of the crop window.
     */
    void set_crop_window(const ScalarPoint2u &crop_offset,
                         const ScalarVector2u &crop_size);

    /**
     * Set the size of the film.
     *
     * This method will reset the crop window to the full image.
     *
     * The caller is responsible to invoke the `parameters_changed()` method on
     * any sensor referring to this film.
     *
     * Args:
     *     size: The new size of the film.
     */
    void set_size(const ScalarPoint2u &size);

    /// Return the image reconstruction filter (const version)
    const ReconstructionFilter *rfilter() const {
        return m_filter.get();
    }

    /// Crop window and related constants as JIT variables, see \ref launch_params()
    struct LaunchParams {
        Vector2u crop_size;
        Point2u crop_offset;

        /// ``dr::divisor`` constants for the row width (crop width plus twice
        /// the filter border when \ref sample_border() is set)
        UInt32 width_mul, width_shift;
    };

    /**
     * \brief Return the crop window and related constants as JIT variables,
     * which keeps the resolution out of code generated by vectorized integrators
     */
    LaunchParams launch_params() const;

    /**
     * Return the Sensor Response Function (SRF) of spectral films, which
     * sensors use to sample wavelengths. Returns ``nullptr`` for other films.
     */
    const Texture *sensor_response_function();

    void traverse(TraversalCallback *callback) override;
    void parameters_changed(const std::vector<std::string> &/*keys*/ = {}) override;

    // =============================================================

    std::string to_string() const override;

    MI_DECLARE_PLUGIN_BASE_CLASS(Film)
protected:
    /// Create a film
    Film(const Properties &props);

    /**
     * Allocate the sample storage for the current channel configuration
     *
     * Subclasses call this at the end of their constructor. The storage
     * exists before the first render so that frozen functions see a stable
     * set of variables.
     */
    void alloc_storage();

    /// Rebuild the buffer underlying \ref launch_params()
    void update_launch_params();

protected:
    ScalarVector2u m_size;
    ScalarVector2u m_crop_size;
    ScalarPoint2u m_crop_offset;
    bool m_sample_border;
    ref<ReconstructionFilter> m_filter;
    ref<Texture> m_srf;
    std::vector<ref<PostProcess>> m_postprocess;

    /// File and component format used by `write()`
    Bitmap::FileFormat m_file_format;
    sj::Type m_component_format;

    /// Sample storage, see the class documentation for its layout
    ref<ImageBlock> m_storage;
    mutable std::mutex m_mutex;

    /// Base channels and channels of the developed image
    std::vector<std::string> m_base_channels, m_channels;

    /// Buffer underlying \ref launch_params()
    DynamicBuffer<UInt32> m_launch_params;

    MI_DECLARE_TRAVERSE_CB(m_filter, m_srf, m_postprocess, m_storage, m_launch_params)
};

MI_EXTERN_CLASS(Film)
NAMESPACE_END(mitsuba)
