name: Windows build

on: [push, pull_request]

jobs:
  build:
    name: Windows build (MSVC, amd64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GHA_TOKEN }}
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install pytest numpy

      - name: Update CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build -DMTS_DEFAULT_VARIANTS="scalar_rgb;scalar_spectral;llvm_ad_rgb" -DPython_ROOT_DIR="$env:pythonLocation"

      - name: Download LLVM (12.0.1)
        run: |
          Invoke-WebRequest "https://rgl.s3.eu-central-1.amazonaws.com/media/uploads/wjakob/2021/09/09/llvm-c.dll" -OutFile "build/LLVM-C.dll"

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - uses: actions/upload-artifact@v2
        with:
          name: mitsuba2-next-win64.zip
          path: build/Release/

      - name: Run test suite
        run: |
          cd build/Release
          ./setpath.ps1
          python -m pytest -v --color yes
