name: build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

concurrency:
  group: build-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: build & test
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/test-build.yml
    with:
      os: windows-latest
